In [1]:
import numpy as np
import pandas as pd

In [2]:
df_qchat_dataset = pd.read_csv('C:\\Users\\hemas\\Documents\\Applied_AI_and_ML_Courses\\Projects_In_Machine_Learning\\ASDInsight\\api_server\\data_collection\\upload\\qchat\\QCHAT_dataset.csv')

In [3]:
display(df_qchat_dataset)

,child_id,age,sex,group,preterm,birthweight,siblings_yesno,siblings_number,mothers_education,sibling_withASD,...,qchat16recode,qchat17recode,qchat18recode,qchat19recode,qchat20recode,qchat21recode,qchat22recode,qchat23recode,qchat24recode,qchat25recode
0,220,18.0,1.0,1.0,1.0,1500.0,0.0,0.0,2.0,0.0,...,2.0,3.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
1,FS/1642,18.0,1.0,1.0,1.0,1700.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,2.0
2,340,18.0,1.0,1.0,1.0,1820.0,0.0,0.0,3.0,0.0,...,0.0,1.0,0.0,3.0,4.0,2.0,2.0,3.0,0.0,0.0
3,FS/2571,18.0,1.0,1.0,1.0,1820.0,0.0,0.0,3.0,0.0,...,3.0,0.0,0.0,2.0,2.0,2.0,0.0,2.0,1.0,1.0
4,236,18.0,1.0,1.0,1.0,2360.0,1.0,1.0,3.0,1.0,...,0.0,0.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,bdbp0245,24.0,2.0,7.0,1.0,4090.0,1.0,2.0,3.0,0.0,...,2.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,1.0,0.0
248,bdbp0500,24.0,1.0,7.0,0.0,4140.0,1.0,1.0,3.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
249,bdbp0162,24.0,1.0,7.0,0.0,4150.0,1.0,1.0,2.0,0.0,...,2.0,1.0,2.0,1.0,0.0,2.0,2.0,2.0,1.0,0.0
250,FS/2311,24.0,1.0,7.0,0.0,NaN,0.0,0.0,3.0,0.0,...,0.0,1.0,4.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0
251,bdbp0096,24.0,2.0,7.0,0.0,NaN,0.0,0.0,3.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df_qchat_dataset.isnull().sum()

child_id              0
age                   0
sex                   0
group                 0
preterm               0
birthweight          12
siblings_yesno        5
siblings_number      23
mothers_education    11
sibling_withASD      22
Sum_QCHAT             0
qchat1recode          0
qchat2recode          0
qchat3recode          0
qchat4recode          0
qchat5recode          0
qchat6recode          0
qchat7recode          0
qchat8recode          0
qchat9recode          0
qchat10recode         0
qchat11recode         0
qchat12recode         0
qchat13recode         0
qchat14recode         0
qchat15recode         0
qchat16recode         0
qchat17recode         0
qchat18recode         0
qchat19recode         0
qchat20recode         0
qchat21recode         0
qchat22recode         0
qchat23recode         0
qchat24recode         0
qchat25recode         0
dtype: int64

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
# Handling `{'$numberDouble': 'NaN'}` entries for all columns
df = df_qchat_dataset.applymap(lambda x: np.nan if isinstance(x, dict) and '$numberDouble' in x and x['$numberDouble'] == 'NaN' else x)

In [7]:
display(df)

,child_id,age,sex,group,preterm,birthweight,siblings_yesno,siblings_number,mothers_education,sibling_withASD,...,qchat16recode,qchat17recode,qchat18recode,qchat19recode,qchat20recode,qchat21recode,qchat22recode,qchat23recode,qchat24recode,qchat25recode
0,220,18.0,1.0,1.0,1.0,1500.0,0.0,0.0,2.0,0.0,...,2.0,3.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
1,FS/1642,18.0,1.0,1.0,1.0,1700.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,2.0
2,340,18.0,1.0,1.0,1.0,1820.0,0.0,0.0,3.0,0.0,...,0.0,1.0,0.0,3.0,4.0,2.0,2.0,3.0,0.0,0.0
3,FS/2571,18.0,1.0,1.0,1.0,1820.0,0.0,0.0,3.0,0.0,...,3.0,0.0,0.0,2.0,2.0,2.0,0.0,2.0,1.0,1.0
4,236,18.0,1.0,1.0,1.0,2360.0,1.0,1.0,3.0,1.0,...,0.0,0.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,bdbp0245,24.0,2.0,7.0,1.0,4090.0,1.0,2.0,3.0,0.0,...,2.0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,1.0,0.0
248,bdbp0500,24.0,1.0,7.0,0.0,4140.0,1.0,1.0,3.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
249,bdbp0162,24.0,1.0,7.0,0.0,4150.0,1.0,1.0,2.0,0.0,...,2.0,1.0,2.0,1.0,0.0,2.0,2.0,2.0,1.0,0.0
250,FS/2311,24.0,1.0,7.0,0.0,NaN,0.0,0.0,3.0,0.0,...,0.0,1.0,4.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0
251,bdbp0096,24.0,2.0,7.0,0.0,NaN,0.0,0.0,3.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
# Handling `{'$numberDouble': 'NaN'}` entries for all columns
df = df_qchat_dataset.applymap(lambda x: np.nan if isinstance(x, dict) and '$numberDouble' in x and x['$numberDouble'] == 'NaN' else x)

# If sibling_yes_no is 0, then number_of_sibling and sibling_with_ASD should be 0
df.loc[df['siblings_yesno'] == 0, ['siblings_number', 'sibling_withASD']] = 0

# If sibling_yes_no is 1 and number_of_sibling or sibling_with_ASD is null, impute with mean/mode
mean_siblings = df[df['siblings_yesno'] == 1]['siblings_number'].mean()
mode_sibling_asd = df[df['siblings_yesno'] == 1]['sibling_withASD'].mode()[0]

df.loc[df['siblings_yesno'] == 1, 'siblings_number'] = df.loc[df['siblings_yesno'] == 1, 'siblings_number'].fillna(mean_siblings)
df.loc[df['siblings_yesno'] == 1, 'sibling_withASD'] = df.loc[df['siblings_yesno'] == 1, 'sibling_withASD'].fillna(mode_sibling_asd)

# For rows where sibling_yes_no is null, decide on a strategy
# Here, we assume no siblings if sibling_yes_no is null, but this could vary based on context
df['siblings_yesno'].fillna(0, inplace=True)
df.loc[df['siblings_yesno'] == 0, ['siblings_number', 'sibling_withASD']] = 0
#Fill missing birthweight with median
median_birthweight = df['birthweight'].median()
df['birthweight'].fillna(median_birthweight, inplace=True)
# Fill mother's education with mode
mode_education = df['mothers_education'].mode()[0]
df['mothers_education'].fillna(mode_education, inplace=True)
# binary encoding of gender and target variable group
df['sex'] = df['sex'].apply(lambda x: 0 if x == 2 else 1)
df['group'] = df['group'].apply(lambda x: 0 if x == 7 else 1)
# Select columns to normalize (excluding non-numeric columns)
numeric_columns = df.select_dtypes(include=['number']).columns
columns_to_exclude = ['group']  # List of columns to exclude
numeric_columns = [col for col in numeric_columns if col not in columns_to_exclude]
# Initialize StandardScaler
scaler = StandardScaler()
# Fit and transform the data
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

In [10]:
display(df)

,child_id,age,sex,group,preterm,birthweight,siblings_yesno,siblings_number,mothers_education,sibling_withASD,...,qchat16recode,qchat17recode,qchat18recode,qchat19recode,qchat20recode,qchat21recode,qchat22recode,qchat23recode,qchat24recode,qchat25recode
0,220,-1.475046,0.777879,1,2.720294,-2.845064,-1.074172,-0.898457,-1.088745,-0.331862,...,0.311238,1.185445,0.582895,0.596033,-0.500995,-1.062300,-0.964022,-0.761413,-1.093812,-0.793183
1,FS/1642,-1.475046,0.777879,1,2.720294,-2.531539,-1.074172,-0.898457,0.604858,-0.331862,...,-1.197068,-0.828480,-0.923665,-0.140243,-0.500995,-0.109632,-0.964022,0.892691,-1.093812,0.999481
2,340,-1.475046,0.777879,1,2.720294,-2.343424,-1.074172,-0.898457,0.604858,-0.331862,...,-1.197068,-0.157171,-0.923665,1.332309,3.506965,0.843035,1.383162,1.719744,-1.093812,-0.793183
3,FS/2571,-1.475046,0.777879,1,2.720294,-2.343424,-1.074172,-0.898457,0.604858,-0.331862,...,1.065391,-0.828480,-0.923665,0.596033,1.502985,0.843035,-0.964022,0.892691,-0.008613,0.103149
4,236,-1.475046,0.777879,1,2.720294,-1.496907,0.930949,0.464203,0.604858,3.013304,...,-1.197068,-0.828480,-0.170385,1.332309,2.504975,-1.062300,-0.964022,-0.761413,-1.093812,0.999481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,bdbp0245,1.413904,-1.285547,0,2.720294,1.215083,0.930949,1.826863,0.604858,-0.331862,...,0.311238,-0.828480,-0.170385,-0.876519,-0.500995,0.843035,0.209570,-0.761413,-0.008613,-0.793183
248,bdbp0500,1.413904,0.777879,0,-0.367607,1.293464,0.930949,0.464203,0.604858,-0.331862,...,-0.442915,-0.828480,2.089455,-0.876519,-0.500995,-0.109632,0.209570,-0.761413,-0.008613,-0.793183
249,bdbp0162,1.413904,0.777879,0,-0.367607,1.309141,0.930949,0.464203,-1.088745,-0.331862,...,0.311238,-0.157171,0.582895,-0.140243,-0.500995,0.843035,1.383162,0.892691,-0.008613,-0.793183
250,FS/2311,1.413904,0.777879,0,-0.367607,0.090313,-1.074172,-0.898457,0.604858,-0.331862,...,-1.197068,-0.157171,2.089455,-0.876519,-0.500995,-1.062300,1.383162,-0.761413,-0.008613,-0.793183
251,bdbp0096,1.413904,-1.285547,0,-0.367607,0.090313,-1.074172,-0.898457,0.604858,-0.331862,...,-1.197068,-0.828480,-0.170385,-0.876519,-0.500995,-1.062300,-0.964022,-0.761413,-1.093812,-0.793183

In [12]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


# Assuming 'target' is the name of your target variable
X = df.drop(columns =['child_id','group'], axis=1)  # Features
y = df['group']                # Target

In [13]:
# Initialize k-fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

In [14]:
# Lists to store evaluation metrics
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
confusion_matrices = []

In [16]:
# Perform k-fold cross-validation
for fold, (train_index, test_index) in enumerate(kf.split(X), 1):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Initialize and train the model
    model = LogisticRegression()
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='binary')
    recall = recall_score(y_test, y_pred, average='binary')
    f1 = f1_score(y_test, y_pred, average='binary')
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Append metrics
    accuracy_scores.append(accuracy)
    precision_scores.append(precision)
    recall_scores.append(recall)
    f1_scores.append(f1)
    confusion_matrices.append(conf_matrix)
    
    # Print metrics for the current fold
    print(f'Fold {fold} - Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'Confusion Matrix:\n{conf_matrix}\n')

Fold 1 - Accuracy: 0.8077, Precision: 0.7857, Recall: 0.8462, F1 Score: 0.8148
Confusion Matrix:
[[10  3]
 [ 2 11]]

Fold 2 - Accuracy: 1.0000, Precision: 1.0000, Recall: 1.0000, F1 Score: 1.0000
Confusion Matrix:
[[11  0]
 [ 0 15]]

Fold 3 - Accuracy: 0.9200, Precision: 0.9286, Recall: 0.9286, F1 Score: 0.9286
Confusion Matrix:
[[10  1]
 [ 1 13]]

Fold 4 - Accuracy: 0.8000, Precision: 0.7500, Recall: 0.9231, F1 Score: 0.8276
Confusion Matrix:
[[ 8  4]
 [ 1 12]]

Fold 5 - Accuracy: 0.8800, Precision: 1.0000, Recall: 0.7500, F1 Score: 0.8571
Confusion Matrix:
[[13  0]
 [ 3  9]]

Fold 6 - Accuracy: 0.7600, Precision: 0.6429, Recall: 0.9000, F1 Score: 0.7500
Confusion Matrix:
[[10  5]
 [ 1  9]]

Fold 7 - Accuracy: 0.9600, Precision: 1.0000, Recall: 0.9444, F1 Score: 0.9714
Confusion Matrix:
[[ 7  0]
 [ 1 17]]

Fold 8 - Accuracy: 0.9200, Precision: 1.0000, Recall: 0.8571, F1 Score: 0.9231
Confusion Matrix:
[[11  0]
 [ 2 12]]

Fold 9 - Accuracy: 0.8400, Precision: 0.9000, Recall: 0.7500, F1 Score: 0.8182
Confusion Matrix:
[[12  1]
 [ 3  9]]

Fold 10 - Accuracy: 0.8800, Precision: 0.8667, Recall: 0.9286, F1 Score: 0.8966
Confusion Matrix:
[[ 9  2]
 [ 1 13]]

In [19]:
# Create a DataFrame to display metrics for all folds
results_df = pd.DataFrame({
    'Fold': range(1, 11),
    'Accuracy': accuracy_scores,
    'Precision': precision_scores,
    'Recall': recall_scores,
    'F1 Score': f1_scores
})

# Print the results as a table
print("\nMetrics for Each Fold:")
display(results_df)

# Calculate and print average performance metrics
average_metrics = pd.DataFrame({
    'Metric': ['Average Accuracy', 'Average Precision', 'Average Recall', 'Average F1 Score'],
    'Value': [
        sum(accuracy_scores) / len(accuracy_scores),
        sum(precision_scores) / len(precision_scores),
        sum(recall_scores) / len(recall_scores),
        sum(f1_scores) / len(f1_scores)
    ]
})

print("\nAverage Metrics:")
display(average_metrics)

Metrics for Each Fold:

   Fold  Accuracy  Precision    Recall  F1 Score
0     1  0.807692   0.785714  0.846154  0.814815
1     2  1.000000   1.000000  1.000000  1.000000
2     3  0.920000   0.928571  0.928571  0.928571
3     4  0.800000   0.750000  0.923077  0.827586
4     5  0.880000   1.000000  0.750000  0.857143
5     6  0.760000   0.642857  0.900000  0.750000
6     7  0.960000   1.000000  0.944444  0.971429
7     8  0.920000   1.000000  0.857143  0.923077
8     9  0.840000   0.900000  0.750000  0.818182
9    10  0.880000   0.866667  0.928571  0.896552

Average Metrics:

              Metric     Value
0   Average Accuracy  0.876769
1  Average Precision  0.887381
2     Average Recall  0.882796
3   Average F1 Score  0.878735